[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = ".vitepress/dist"
  command = "npx pnpm i --frozen-lockfile --store=node_modules/.pnpm-store && npm run build"
