name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install npm
        uses: npm/action-setup@v2
        with:
          version: 6

      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install deps
        run: npm install

      - name: Build
        run: npm build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install npm
        uses: npm/action-setup@v2
        with:
          version: 6

      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: npm install

      - name: Lint
        run: npm lint
